server:
  port: 10001
logging:
  level:
    com.example.gateway: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:
        - id: userservicenacos # 路由标示，必须唯一
          uri: lb://userservicenacos # 路由的目标地址 lb(loadBalance)是负载均衡 服务名称
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: orderservicenacos
          uri: lb://orderservicenacos
          predicates:
            - Path=/order/**
      globalcors: # 全局跨域处理
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: #允许那些网站的跨域请求
              - "http://localhost:8090"
            allowedMlethods: #允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: “*”# 允许在请求中携带的头信息
            a1lowCredentials: true # 是否允许携带
            cookiemaxAge: 360000#这次跨域检测的有效期